### ISSUE TITLE
 communication problem

### ISSUE THREAD

**Issue by TVDB0174** [sequ3ster/protocol-max#3]
Hello, I’m currently trying to control the EVBox Business Line using an ASCII string. I have constructed my ASCII string according to the specifications of the Max protocol. Since multiple EVs are connected to the backend, I need to use Max protocol 68, which includes the serial number. I am directly connected to the EVBox using an RS485 converter from my COM port. When I send the message 
 STX 80A0680192305400112233445566778899AABBCCDDEEFF006400640064003C003C003C003CE17B ETX , I don’t receive any reply. Can you help me with this? Thank you very much!

**Comment by sequ3ster** [comment]
Hello, for more than 1.5 years I have not dealt with the subject and will not get to it in the foreseeable future. I am sorry to tell you that I can not help you.
